name: flutter-android-build-e
description: 'ðŸ— Easy to use flutter android build action, support custom base directory'
author: xiaoxiao921
branding:
  icon: 'zap'
  color: 'black'

inputs:
  release:
    description: 'If set to `true`, it will run release builds, otherwise debug builds'
    required: false
    default: false
  build-type:
    description: 'apk | aab | both'
    required: false
    default: both
  keystore:
    description: 'Base64 encoded keystore.jks, required if release is true'
    required: false
    default: ''
  keystore-pwd:
    description: 'keystore password, required if release is true'
    required: false
    default: ''
  key-pwd:
    description: 'key password, required if release is true'
    required: false
    default: ''
  base-directory:
    description: 'base directory'
    required: false
    default: ''

outputs:
  apk-path:
    description: "Path to built apk if build-type was set to apk or both"
    value: ${{ steps.path-output.outputs.apk-path }}
  aab-path:
    description: "Path to built aab if build-type was set to aab or both"
    value: ${{ steps.path-output.outputs.aab-path }}

runs:
  using: "composite"
  steps:
    - env:
        KEY_PWD: ${{ inputs.key-pwd }}
        KEYSTORE_PWD: ${{ inputs.keystore-pwd }}
      run: |
        if [ -n "${{ inputs.base-directory }}" ]; then
          cd ${{ inputs.base-directory }}
        fi
      
        flutter pub get

        flutter pub run build_runner build --delete-conflicting-outputs

        echo "${{ inputs.keystore }}" | base64 -d > android/keystore.jks

        # build
        if [ ${{ inputs.release }} = "true" ]; then

          if [ ${{ inputs.build-type }} = "apk" ] || [ ${{ inputs.build-type }} = "both" ]; then
            flutter build apk || true
          fi
          if [ ${{ inputs.build-type }} = "aab" ] || [ ${{ inputs.build-type }} = "both" ]; then
            flutter build appbundle || true
          fi

        else

          if [ ${{ inputs.build-type }} = "apk" ] || [ ${{ inputs.build-type }} = "both" ]; then
            flutter build apk --debug || true
          fi
          if [ ${{ inputs.build-type }} = "aab" ] || [ ${{ inputs.build-type }} = "both" ]; then
            flutter build appbundle --debug || true
          fi
        fi

        # release
        if [ ${{ inputs.release }} = "true" ]; then
    
          if [ ${{ inputs.build-type }} = "apk" ] || [ ${{ inputs.build-type }} = "both" ]; then
            if [ -z "${{ inputs.base-directory }}" ]; then
                APK_PATH="build/app/outputs/flutter-apk/app-release.apk"
            else
                APK_PATH="${{ inputs.base-directory }}/build/app/outputs/flutter-apk/app-release.apk"
            fi
            
            if [ ! -f $APK_PATH ]; then
              exit 1
            fi
            echo "::set-output name=apk-path::$(echo $APK_PATH)"
          fi
    
          if [ ${{ inputs.build-type }} = "aab" ] || [ ${{ inputs.build-type }} = "both" ]; then
            if [ -z "${{ inputs.base-directory }}" ]; then
                APK_PATH="build/app/outputs/bundle/release/app-release.aab"
            else
                APK_PATH="${{ inputs.base-directory }}/build/app/outputs/bundle/release/app-release.aab"
            fi
            
            if [ ! -f $AAB_PATH ]; then
              exit 1
            fi
            echo "::set-output name=aab-path::$(echo $AAB_PATH)"
          fi
    
        else
    
          if [ ${{ inputs.build-type }} = "apk" ] || [ ${{ inputs.build-type }} = "both" ]; then
            if [ -z "${{ inputs.base-directory }}" ]; then
                APK_PATH="build/app/outputs/flutter-apk/app-debug.apk"
            else
                APK_PATH="${{ inputs.base-directory }}/build/app/outputs/flutter-apk/app-debug.apk"
            fi

            if [ ! -f $APK_PATH ]; then
              exit 1
            fi
            echo "::set-output name=apk-path::$(echo $APK_PATH)"
          fi
    
          if [ ${{ inputs.build-type }} = "aab" ] || [ ${{ inputs.build-type }} = "both" ]; then
            if [ -z "${{ inputs.base-directory }}" ]; then
                APK_PATH="build/app/outputs/bundle/debug/app-debug.aab"
            else
                APK_PATH="${{ inputs.base-directory }}/build/app/outputs/bundle/debug/app-debug.aab"
            fi
            
            if [ ! -f $AAB_PATH ]; then
              exit 1
            fi
            echo "::set-output name=aab-path::$(echo $AAB_PATH)"
          fi
        fi
      shell: bash
      id: path-output


